Improve error logging for ReportingService
wavefrontHQ/wavefront-sdk-java pull request #168
Opened 2020-09-18 17:25 UTC by xshipeng

The SEVER level log message in ReportingService will only appear after 5 minutes of continuous connection failure.

2020-09-18 22:40 UTC, hanwavefront requested changes
a couple minor things, otherwise lgtm

2020-09-18 22:40 UTC, hanwavefront commented on src/main/java/com/wavefront/sdk/common/logging/DelegatingLogger.java
> +   void inferCaller(LogRecord logRecord) {
nit: formatting

2020-09-18 22:40 UTC, hanwavefront commented on src/main/java/com/wavefront/sdk/common/clients/service/ReportingService.java
> +              + urlConn.getURL().toString());
Let's log the exception message to provide some additional context.  E.g., ` + " due to: " + ex.getMessage()`

2020-09-18 22:40 UTC, hanwavefront commented on src/main/java/com/wavefront/sdk/common/clients/service/ReportingService.java
> +              + urlConn.getURL().toString());
Ditto, let's log the exception message.

2020-09-18 22:40 UTC, hanwavefront commented on src/main/java/com/wavefront/sdk/common/logging/MessageSuppressingLogger.java
> +        logRecord.setSourceClassName(className);
Does the infer work correctly if you call `logger.severe(msg)`?  For this case, I think we might still need the if statement that's here in the parent method.  Let's add an assert to the tests to check the source class and method name too.

2020-09-19 00:50 UTC, hanwavefront approved these changes
LGTM, just one nit

2020-09-19 00:50 UTC, hanwavefront commented on src/main/java/com/wavefront/sdk/common/logging/MessageSuppressingLogger.java
> +            && !cname.startsWith("com.google.common.cache.LocalCache")) {
nit: move && to end of previous line

2020-09-21 18:47 UTC, sushantdewan123 approved these changes

2020-09-21 18:47 UTC, merged